name: NodeJS with Grunt

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --dev

    - name: Test
      run: npm run test:unit

    - name: Build
      run: npm run bundle

    - name: Push artifacts
      uses: actions/upload-artifact@v7
      with:
        name: build
        path: ./query-params-conditional-visibility.zip
